version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: forum-postgres
    environment:
      POSTGRES_DB: forum_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - forum-network

  forum-server:
    build: .
    container_name: forum-server
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/forum_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: password
    depends_on:
      - postgres
    volumes:
      - ./uploads:/app/uploads
    networks:
      - forum-network

volumes:
  postgres_data:

networks:
  forum-network:
    driver: bridge 